name: ⭐ Request a new feature
description: Have an idea? You can request a new feature here.
labels: [enhancement,under review]
body:
  - type: dropdown
    id: version
    attributes:
      label: 🔢 Version
      description: Which version of Glitter.Extensions are you currently using?
      options:
        - 🐬 2023.5.21
        - 💀 2023.1.0.0
        - 🐣 Pre-Release
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🤔 What problem does your proposition aim to solve?
      description: If your feature request is related to a problem, describe it clearly.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📝 How would you like the feature to work?
      description: Please give a brief explanation and a sample implementation.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🧪 What have you already tried?
      description: Describe alternatives you've considered.